[project]
name = "Do It Yourself Tools"
version = "0.1.0"
description = "Add a short description here"

authors = [
	"Tim-Oliver Buchholz <tim-oliver.buchholz@fmi.ch>",
	"Jan Eglinger <jan.eglinger@fmi.ch",
  "Laure Plantard <laure.plantard@fmi.ch>",
  "Laurent Gelman <laurent.gelman@fmi.ch>",
  "Sabine Reither <sabine.reither@fmi.ch>",
]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64", "win-64", "osx-arm64", "osx-64"]

[system-requirements]
# See https://pixi.sh/latest/features/system_requirements/#default-system-requirements

[dependencies]
python = "3.12"

[feature.docs.dependencies]
mkdocs = ">=1.6.0,<2"
mkdocs-git-committers-plugin-2 = ">=2.3.0,<3"
mkdocs-git-revision-date-localized-plugin = ">=1.2.6,<2"
mkdocs-material = ">=9.5.31,<10"
mkdocstrings = ">=0.25.2,<0.26"
mkdocstrings-python = ">=1.10.7,<2"

[feature.docs.tasks]
clean_docs = "rm -rf site"
build_docs = { cmd ="OFFLINE=TRUE mkdocs build", depends_on=["clean_docs"] }
show_docs = "mkdocs serve"

[feature.dev.dependencies]
pre-commit = ">=3.1.1,<3.8"

[feature.dev.tasks]
install_hooks = "pre-commit install"
lint = { cmd="pre-commit run --all-files", depends_on=["install_hooks"] }

[environments]
docs = { features = ["docs"], solve-group="default" }
dev = { features = ["dev"], solve-group="default" }
